### ISSUE TITLE
Problem of incomplete test data and installing mm10 database

### ISSUE THREAD

**Issue by gundalav** [BulykLab/MEDEA#1]
Hi, 

I downloaded the MEDEA code from here:

`git clone https://github.com/BulykLab/MEDEA.git`

And try to follow instruction with this:

`python format.py`

However, I get this error:

```
Starting /home/ubuntu/gundalav/tmp/MEDEA/data/GENRE/hg19/db/hg19_DNaseSeq/hg19BGpool_multLen150x150.bed.gz
Traceback (most recent call last):
  File "format.py", line 56, in <module>
    raise Exception("gunzip failed.")
Exception: gunzip failed.
```

Apparently the data 

`data/GENRE/hg19/db/hg19_DNaseSeq/hg19BGpool_multLen150x150.bed.gz`

is faulty, size is only few bytes.
Is there a way to resolve this problem?

Moreover is there a way I can install database for `mm10`?

**Comment by keweinan** [comment]
Hello,

Thanks for downloading MEDEA! I'm happy to help with the installation.

That particular file is a bit large, and thus requires git lfs for proper
downloading. Have you installed git lfs?

Another way around using git lfs is to download the zip file from GitHub
and add the -zip flag to format.py, i.e.,
$ python format.py -zip

We do have a database for mm10, but my collaborators and I are discussing
whether to release it now or wait for an upcoming manuscript. However,
while that database would work for GENRE, we do not have a default mm10
reference set for MEDEA, so you would have to provide that.

Please let me know if you have any other questions! Thanks!

Katy Weinand
PhD student in Bioinformatics and Integrative Genomics
Harvard Medical School

**Comment by gundalav** [comment]
Hi Katy, 

Thank you for prompt response.
Is there any documentation or code that allow us to make mm10 reference set?

G.V.

**Comment by keweinan** [comment]
The reference set is a collection of narrowPeak files: chromatin accessibility peaksets, 1 file per cell line. BED files would also work. There isn't any code to make it; it's something that needs to be curated from the field or generated in house. For the hg19 genome, we used the ENCODE-DREAM curated peaksets from: https://www.synapse.org/#!Synapse:syn6176236. Individual IDs can be found in Supplemental Table 1 in the accompanying paper.

There is a script to add a new reference set to MEDEA should you find or curate your own high quality mm10 chromatin accessibility peaksets in bin/MEDEA/addRefSet.

**Comment by gundalav** [comment]
I tried the following line:

`bin/MEDEA/addRefSet mm10 data/GENRE`

to add new mm10 as you suggested.

But gives me:

```
Traceback (most recent call last):
  File "bin/MEDEA/addRefSet", line 34, in <module>
    raise Exception("The fasta file for the genome you've selected doesn't exist. Please download the appropriate genome from getGENRE.py and try again.")
Exception: The fasta file for the genome you've selected doesn't exist. Please download the appropriate genome from getGENRE.py and try again.
```

Did I miss anything?

**Comment by keweinan** [comment]
MEDEA is built off of our previous software Glossary-GENRE. Since we didn’t initially plan to release the mm10 GENRE database, I didn’t include the mm10 genome fasta file in this repo. I can likely add the genome file without any consequences with the current release, but let me sleep on it. However, it would only help with MEDEA pairwise subtraction at this point, not the entire pipeline without a corresponding GENRE database.

Also, the second argument must be a directory of bed or narrowPeak files, not data/GENRE, so that command would have failed anyway. MEDEA verifies that the inputted files are BED derived in the indicated genome, hence the need for a genome fasta file.

**Comment by gundalav** [comment]
I can successfully install the refset with this command

`bin/MEDEA/addRefSet mm10 /home/ubuntu/storage2/Tools/MEDEA/data/GENRE/mm10/db/mm10.pseudoDNASeq`

Basically the peak set contain the 1 million random peaks of size 150 bp sampled from the genome.

However I can't make the `db` file as you made here:

```
./hg19/db/hg19_DNaseSeq/hg19BGpool_multLen150x150.db
./hg19/db/hg19_DNaseSeq/exTbl.txt
```

Please advice how can I make it?

**Comment by keweinan** [comment]
How did you install the refset without the mm10 genome file? Or did you provide one in the correct directory yourself?

Yes, those files require GENRE scripts. After much consideration, we have decided to provide GENRE databases for a few other genomes, including mm10. Those will go up sometime this weekend.

**Comment by gundalav** [comment]
> Yes, those files require GENRE scripts. After much consideration, we have decided to provide GENRE databases for a few other genomes, including mm10. Those will go up sometime this weekend.

Thanks so much for making mm10 available. Look forward for it.

**Comment by keweinan** [comment]
The mm10 genome and GENRE database have been added. The motif sets provided should still work for this genome. Please let me know if these files don't work for you.

**Comment by gundalav** [comment]
Thank you I successfully installed this latest version with mm10.
However I can't find the refSet file; in hg19 we have 
`MEDEA reference sets (ref_ID): hg19_ENCODE-DREAM_DNase_relaxed`
but not for `mm10`.


How and where can I get the corresponding files for `mm10`?
If I were to make the refset myself in-house, what is the criteria to make those?

I'm thinking to get it from ENCODE mm10 related DNAse [**here**](https://www.encodeproject.org/matrix/?searchTerm=dnase-seq&type=Experiment&files.file_type=fastq&award.project=ENCODE&assembly=mm10&biosample_ontology.classification=cell+line).

But I'm not sure if it's reasonable or not. 
Please advice.

**Comment by keweinan** [comment]
We do not have reference sets for these other genomes at this time. They are not something we make with our pipelines, but rather curated from the datasets in the field.

To make your own reference set, we have put together some guidelines in the last part of the MEDEA inputs section of the README.

We have certainly used the ENCODE data matrix in the past, but we stipulate that the more rigorous QC of the reference datasets before they are added to MEDEA, the better the results will be afterwards.

Please let me know if that sufficiently answers your questions. If so, I will close this issue. Thanks!

**Comment by gundalav** [comment]
Thank you. Please close the issue.
